/**
 * The JuryAI P2 case-formation runtime.
 *
 * This is the layer between a transport (WebMCP tools, first-party HTTP, file
 * import) and the canonical core. It is deliberately transport-independent:
 * it takes a trusted principal context that the transport has already
 * resolved, and returns canonical outcomes that a transport renames but never
 * reinterprets.
 *
 * The order of operations in `submitTurn` is the architecture, not an
 * implementation detail. In particular idempotency resolution happens BEFORE
 * version validation. "Have I already done this?" is logically prior to "is
 * this valid against current state?", and reversing them makes every
 * lost-response retry fail: the caller refreshes, retries with the new
 * version, and records the same statement twice.
 *
 * What this runtime does NOT do:
 *  - It does not register WebMCP tools.
 *  - It does not attest, lock, or expose attestation. Case formation only.
 *  - It does not let the semantic compiler write to canonical state.
 *  - It does not surface validator or compiler internals to a caller.
 */

import { deriveCaseStatus, projectCaseState, type CaseState } from '../core/attestation.js';
import {
  buildCompileRunRecord,
  buildCompilerInput,
  type CompileRunRecord,
  type CompilerOutput,
} from '../core/compiler-contract.js';
import {
  precheckSubmit,
  validateSubmitRequest,
  type IdempotencyRecord,
  type StoredSubmitResponse,
  type SubmitRequest,
} from '../core/idempotency.js';
import { livePropositions, type Proposition } from '../core/propositions.js';
import { validateCaseState } from '../core/structural-validator.js';
import {
  appendTurn,
  computePayloadCommitment,
  normalizePayload,
  validatePayloadShape,
  validateSourceTurnRecord,
  type SourceTurnPayload,
  type SourceTurnRecord,
} from '../core/turns.js';
import type { CaseStateResponse, SourceChannel } from '../core/types.js';
import type { SemanticCompilerPort } from './compiler-port.js';
import {
  isoFrom,
  type PayloadSaltFactory,
  type RuntimeClock,
  type RuntimeIdFactory,
} from './ids.js';
import {
  defaultRequirementSetProvider,
  type RequirementSetProvider,
} from './initial-requirements.js';
import { applyCompilerOutput } from './mutation-application.js';
import { ActiveDraftExistsError, type CaseRuntimeStore, type StoredCase } from './repositories.js';
import {
  failure,
  interpretationSlot,
  noopDiagnosticsSink,
  type GetCaseStateOutcome,
  type RuntimeDiagnosticsSink,
  type StartCaseOutcome,
  type SubmitTurnOutcome,
} from './results.js';

/* ------------------------------------------------------------------------ */
/* Trusted request context                                                   */
/* ------------------------------------------------------------------------ */

/**
 * The authenticated principal, resolved by the transport from a session. A
 * principal id appearing anywhere in external tool input is data, never
 * identity, and this runtime never reads one from a command.
 */
export interface RuntimePrincipal {
  principal_id: string;
}

export interface RuntimeRequestContext {
  principal: RuntimePrincipal;
  /**
   * Where the text reached JuryAI from. Resolved by the transport, never by
   * the caller: relayed input cannot promote itself to first-party
   * provenance by asking. Defaults to the relay channel.
   */
  source_channel?: SourceChannel;
  /** Relay's self-reported identity. Recorded for the record, never trusted. */
  relaying_agent?: string | null;
}

/**
 * Per-call execution context. Deliberately separate from the command: an
 * `AbortSignal` is how the caller is still listening, not something the case
 * records. Nothing here ever reaches canonical state.
 */
export interface RuntimeCallOptions {
  signal?: AbortSignal;
}

export interface GetCaseStateQuery {
  /** Omitted means "the authenticated principal's active draft". */
  case_id?: string;
}

export interface SubmitTurnCommand {
  case_id: string;
  expected_case_version: number;
  in_reply_to: string[];
  payload: SourceTurnPayload;
  /** Adapter-minted retry key. Never generated by a model. */
  client_turn_id: string | null;
  /** Self-reported by the relay. Recorded, never trusted. */
  source_language?: string | null;
  translation_indicated?: boolean;
}

/* ------------------------------------------------------------------------ */
/* Dependencies                                                              */
/* ------------------------------------------------------------------------ */

export interface DisclosureConfig {
  /** Trusted configuration. Never an external-AI-supplied value. */
  version: string;
}

export interface CaseRuntimeDependencies {
  store: CaseRuntimeStore;
  compiler: SemanticCompilerPort;
  clock: RuntimeClock;
  ids: RuntimeIdFactory;
  salts: PayloadSaltFactory;
  /**
   * First-party review entry point for a case. It is one way a human reaches
   * the draft, not the only one: independent first-party discovery of an
   * active draft is a separate product surface and must not depend on the
   * relay having kept this string.
   */
  reviewUrl: (caseId: string) => string;
  disclosure: DisclosureConfig;
  requirements?: RequirementSetProvider;
  diagnostics?: RuntimeDiagnosticsSink;
  fingerprintReplayWindowMs?: number;
  /** Bound on compare-and-swap retries under write contention. */
  maxCommitAttempts?: number;
}

const DEFAULT_MAX_COMMIT_ATTEMPTS = 3;

export class CaseRuntime {
  readonly #deps: CaseRuntimeDependencies;
  readonly #requirements: RequirementSetProvider;
  readonly #diagnostics: RuntimeDiagnosticsSink;
  #compilerRegistered: Promise<void> | null = null;

  constructor(dependencies: CaseRuntimeDependencies) {
    this.#deps = dependencies;
    this.#requirements = dependencies.requirements ?? defaultRequirementSetProvider;
    this.#diagnostics = dependencies.diagnostics ?? noopDiagnosticsSink;
  }

  /* --------------------------------------------------------------------- */
  /* start_case                                                             */
  /* --------------------------------------------------------------------- */

  async startCase(context: RuntimeRequestContext): Promise<StartCaseOutcome> {
    const principalId = principalOf(context);
    if (principalId === null) {
      return { kind: 'failed', failure: failure('AUTH_REQUIRED', 'No authenticated principal.') };
    }

    const existing = await this.#deps.store.cases.findActiveDraftByPrincipal(principalId);
    if (existing) {
      // Never a silent resume: an agent that "starts a case" while one is open
      // must be told, or a second conversation quietly overwrites the first.
      return { kind: 'open_draft_exists', case: this.#project(existing.state) };
    }

    const nowMs = this.#deps.clock.now();
    const state: CaseState = {
      case_id: this.#deps.ids.caseId(),
      case_version: 0,
      principal_id: principalId,
      // Recorded at creation and never backfillable: a disclosure accepted
      // after the fact is not a disclosure.
      disclosure_version: this.#deps.disclosure.version,
      disclosure_accepted_at: isoFrom(nowMs),
      requirements: this.#requirements.initialRequirements(),
      propositions: [],
      clarifications: [],
      evidence_references: [],
      turn_log: [],
      attestations: [],
    };

    const report = validateCaseState(state);
    if (!report.ok) {
      this.#diagnostics.record({
        kind: 'structural_validation_failed',
        case_id: state.case_id,
        turn_id: null,
        compile_run_id: null,
        message: 'Initial case state failed structural validation.',
        issues: report.issues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'The case could not be created.', true),
      };
    }

    try {
      const stored = await this.#deps.store.cases.create(state);
      return { kind: 'created', case: this.#project(stored.state) };
    } catch (error) {
      if (error instanceof ActiveDraftExistsError) {
        // Lost a create race. The other writer's draft is the live one.
        const winner = await this.#deps.store.cases.findActiveDraftByPrincipal(principalId);
        if (winner) return { kind: 'open_draft_exists', case: this.#project(winner.state) };
      }
      this.#diagnostics.record({
        kind: 'case_creation_failed',
        case_id: state.case_id,
        turn_id: null,
        compile_run_id: null,
        message: error instanceof Error ? error.message : 'Case creation failed.',
        issues: [],
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'The case could not be created.', true),
      };
    }
  }

  /* --------------------------------------------------------------------- */
  /* get_case_state                                                         */
  /* --------------------------------------------------------------------- */

  async getCaseState(
    context: RuntimeRequestContext,
    query: GetCaseStateQuery = {},
  ): Promise<GetCaseStateOutcome> {
    const principalId = principalOf(context);
    if (principalId === null) {
      return { kind: 'failed', failure: failure('AUTH_REQUIRED', 'No authenticated principal.') };
    }

    const stored =
      query.case_id === undefined
        ? await this.#deps.store.cases.findActiveDraftByPrincipal(principalId)
        : await this.#deps.store.cases.findById(query.case_id);

    // A foreign case is reported as not found rather than as forbidden: the
    // distinction is an existence oracle over other people's case ids.
    if (!stored || stored.state.principal_id !== principalId) {
      return { kind: 'failed', failure: failure('CASE_NOT_FOUND', 'No such case.') };
    }
    return { kind: 'ok', case: this.#project(stored.state) };
  }

  /* --------------------------------------------------------------------- */
  /* submit_turn                                                            */
  /* --------------------------------------------------------------------- */

  /**
   * Returns a `SubmitTurnOutcome` for every outcome the case can have,
   * including every failure. The single exception is cancellation: if the
   * caller's own signal aborts, that abort is rethrown rather than flattened
   * into a failure, so the transport's execution and retry path can unwind
   * instead of treating a cancelled request as a processing error.
   */
  async submitTurn(
    context: RuntimeRequestContext,
    command: SubmitTurnCommand,
    options: RuntimeCallOptions = {},
  ): Promise<SubmitTurnOutcome> {
    // An already-cancelled call does no work at all: no state read, no
    // compiler execution, no commit.
    options.signal?.throwIfAborted();

    const principalId = principalOf(context);
    if (principalId === null) {
      return { kind: 'failed', failure: failure('AUTH_REQUIRED', 'No authenticated principal.') };
    }

    if (!wellFormedCommand(command)) {
      return {
        kind: 'failed',
        failure: failure('INVALID_INPUT', 'The submission is not well formed.'),
      };
    }

    const payload = normalizePayload(command.payload);
    const payloadIssues = validatePayloadShape(payload, 'payload');
    if (payloadIssues.length > 0) {
      return {
        kind: 'failed',
        failure: failure('INVALID_INPUT', 'The relayed turn payload is not well formed.'),
      };
    }
    const inReplyTo = [...new Set(command.in_reply_to)].sort();
    const request: SubmitRequest = {
      case_id: command.case_id,
      principal_id: principalId,
      expected_case_version: command.expected_case_version,
      in_reply_to: inReplyTo,
      payload,
      client_turn_id: command.client_turn_id,
    };
    const requestIssues = validateSubmitRequest(request, 'submit');
    if (requestIssues.length > 0) {
      return {
        kind: 'failed',
        failure: failure('INVALID_INPUT', 'The submission is not well formed.'),
      };
    }

    try {
      await this.#ensureCompilerRegistered();
    } catch {
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed. Try again.', true),
      };
    }

    const attempts = this.#deps.maxCommitAttempts ?? DEFAULT_MAX_COMMIT_ATTEMPTS;
    for (let attempt = 0; attempt < attempts; attempt += 1) {
      const outcome = await this.#attemptSubmit(
        context,
        principalId,
        request,
        {
          // Self-reported by the relay and recorded as such. A translated
          // answer has no span fidelity to anything the human actually typed,
          // so the claim is stored rather than quietly dropped.
          source_language: command.source_language ?? null,
          translation_indicated: command.translation_indicated === true,
        },
        options,
      );
      if (outcome !== 'contended') return outcome;
    }

    this.#diagnostics.record({
      kind: 'commit_contention_exhausted',
      case_id: request.case_id,
      turn_id: null,
      compile_run_id: null,
      message: 'Exhausted compare-and-swap attempts under write contention.',
      issues: [],
    });
    return {
      kind: 'failed',
      failure: failure('INTERNAL_ERROR', 'The case is busy. Try again.', true),
    };
  }

  /**
   * One full pass of the pipeline against a freshly read case. Returns
   * `'contended'` when the compare-and-swap lost, so the caller re-reads and
   * re-runs from the top: a mutation prepared against superseded state is
   * never rewritten onto the winner.
   */
  async #attemptSubmit(
    context: RuntimeRequestContext,
    principalId: string,
    request: SubmitRequest,
    relayClaims: { source_language: string | null; translation_indicated: boolean },
    options: RuntimeCallOptions,
  ): Promise<SubmitTurnOutcome | 'contended'> {
    const stored = await this.#deps.store.cases.findById(request.case_id);
    if (!stored || stored.state.principal_id !== principalId) {
      return { kind: 'failed', failure: failure('CASE_NOT_FOUND', 'No such case.') };
    }
    const state = stored.state;

    /* --- idempotency first, then the lock, then CAS. --------------------- */
    const idempotencyRecords = await this.#deps.store.idempotency.listByCase(request.case_id);
    const precheck = precheckSubmit(request, {
      store: idempotencyRecords,
      log: state.turn_log,
      current_case_version: state.case_version,
      now_ms: this.#deps.clock.now(),
      window_ms: this.#deps.fingerprintReplayWindowMs,
    });

    if (precheck.kind === 'replay') {
      const previous = precheck.record.response;
      return {
        kind: 'replayed',
        match: precheck.match,
        recorded_at_case_version: previous.case_version,
        turn_id: previous.turn_id,
        case: this.#project(state, previous.warnings),
        recorded: resolveRecorded(state.propositions, previous.accepted_proposition_ids),
        accepted_proposition_ids: [...previous.accepted_proposition_ids],
        superseded_proposition_ids: [...previous.superseded_proposition_ids],
        opened_clarification_ids: [...previous.opened_clarification_ids],
        warnings: [...previous.warnings],
      };
    }

    // Only a genuinely NEW write is refused by the lock. An operation that
    // already happened stays replayable for the lifetime of the case: the
    // caller that lost a response is asking what its earlier write did, and
    // a later attestation does not unmake it. This check sits ahead of the
    // version conflict deliberately — telling a caller its version is stale
    // invites a refresh-and-retry against a case that can never accept it.
    if (deriveCaseStatus(state) === 'locked') {
      return {
        kind: 'failed',
        failure: failure('CASE_LOCKED', 'This case version has been attested and cannot change.'),
      };
    }

    if (precheck.kind === 'version_conflict') {
      return {
        kind: 'version_conflict',
        current_case_version: precheck.current_case_version,
        recent_turns: precheck.recent_turns,
        likely_already_recorded: precheck.likely_already_recorded,
        case: this.#project(state),
      };
    }

    const known = new Set(state.requirements.map((definition) => definition.requirement_id));
    if (request.in_reply_to.some((requirementId) => !known.has(requirementId))) {
      return {
        kind: 'failed',
        failure: failure(
          'INVALID_INPUT',
          'The turn answers a requirement this case does not have.',
        ),
      };
    }

    /* --- immutable source turn ------------------------------------------- */
    const compileRunId = this.#deps.ids.compileRunId();
    const turnId = this.#deps.ids.turnId();
    const salt = this.#deps.salts.next();
    const receivedAtMs = this.#deps.clock.now();
    const turn: SourceTurnRecord = {
      turn_id: turnId,
      case_id: state.case_id,
      case_version_before: state.case_version,
      received_at: isoFrom(receivedAtMs),
      principal_id: principalId,
      source_channel: context.source_channel ?? 'webmcp_agent_relay',
      relaying_agent: context.relaying_agent ?? null,
      source_language: relayClaims.source_language,
      translation_indicated: relayClaims.translation_indicated,
      in_reply_to: [...request.in_reply_to],
      client_turn_id: request.client_turn_id,
      request_fingerprint: precheck.request_fingerprint,
      payload: request.payload,
      payload_commitment_salt: salt,
      payload_commitment: computePayloadCommitment(request.payload, salt),
      compile_run_id: compileRunId,
    };

    const turnIssues = validateSourceTurnRecord(turn, 'turn');
    if (turnIssues.length > 0) {
      this.#diagnostics.record({
        kind: 'source_turn_invalid',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'Constructed source turn failed its own contract.',
        issues: turnIssues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'The turn could not be recorded.', true),
      };
    }

    let nextLog: SourceTurnRecord[];
    try {
      nextLog = appendTurn(state.turn_log, turn);
    } catch {
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'The turn could not be recorded.', true),
      };
    }

    /* --- semantic compilation -------------------------------------------- */
    const compilerInput = buildCompilerInput({
      compile_run_id: compileRunId,
      compiler_version_id: this.#deps.compiler.registryEntry.compiler_version_id,
      state: { case_id: state.case_id, case_version: state.case_version },
      turn,
      requirements: state.requirements,
      livePropositions: livePropositions(state.propositions),
    });

    // Re-checked here as well as at entry: the compare-and-swap retry loop can
    // re-enter this method, and a cancelled call must not start a second
    // expensive execution.
    options.signal?.throwIfAborted();

    const startedAt = isoFrom(this.#deps.clock.now());
    let output: CompilerOutput;
    try {
      output = await this.#deps.compiler.compile(compilerInput, { signal: options.signal });
    } catch (error) {
      // A cancelled execution is not a failed one. Flattening it into
      // INTERNAL_ERROR would tell the transport to consider retrying work the
      // caller has already walked away from.
      if (options.signal?.aborted === true) {
        throw options.signal.reason ?? error;
      }
      this.#diagnostics.record({
        kind: 'compiler_threw',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: error instanceof Error ? error.message : 'Compiler failed.',
        issues: [],
      });
      // Nothing is committed: no turn, no run, no version movement. A retry
      // carrying the same client_turn_id is therefore still a fresh request.
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed. Try again.', true),
      };
    }
    const finishedAt = isoFrom(this.#deps.clock.now());

    /* --- fix the compiler's output at the runtime boundary ---------------- */
    // Everything above this line is ours; `output` is the first object in the
    // pipeline produced outside the runtime. A provider adapter that returns a
    // structurally malformed value makes the core contract check dereference
    // fields that are not there, and an exception thrown here would escape
    // `submitTurn` instead of becoming a runtime failure. The boundary is
    // enforced here rather than by loosening the frozen core validator.
    let runRecord: CompileRunRecord;
    try {
      runRecord = buildCompileRunRecord(compilerInput, output, {
        started_at: startedAt,
        finished_at: finishedAt,
      });
    } catch (error) {
      this.#diagnostics.record({
        kind: 'compiler_contract_violation',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message:
          'Compiler output was too malformed to record as a compile run: ' +
          (error instanceof Error ? error.message : 'unknown error'),
        issues: [],
      });
      // No run record can be built, so none is persisted; the failure lives in
      // the diagnostics sink. Nothing is committed, so the retry key is fresh.
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed.', false),
      };
    }
    // Append-only audit, written whether or not the result is absorbed. A run
    // that happened and was rejected is history; hiding it makes "the compiler
    // never proposed X" indistinguishable from "the runtime refused X".
    try {
      await this.#deps.store.compileRuns.append(runRecord);
    } catch {
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed. Try again.', true),
      };
    }

    if (runRecord.contract_issues.length > 0) {
      this.#diagnostics.record({
        kind: 'compiler_contract_violation',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'Compiler output violated the core contract.',
        issues: runRecord.contract_issues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed.', false),
      };
    }

    /* --- server-owned mutation ------------------------------------------- */
    const nextVersion = state.case_version + 1;
    const mutation = applyCompilerOutput({
      state,
      turn,
      output,
      next_case_version: nextVersion,
      ids: this.#deps.ids,
    });
    if (!mutation.ok) {
      this.#diagnostics.record({
        kind: 'mutation_rejected',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'Compiler output could not be applied to canonical state.',
        issues: mutation.issues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed.', false),
      };
    }

    // The canonical version moves only when the canonical projection moves.
    // Appending a turn that produced nothing canonical is log growth, not a
    // new version of the case.
    const effectiveVersion = mutation.mutation.changed ? nextVersion : state.case_version;
    const nextState: CaseState = {
      ...state,
      case_version: effectiveVersion,
      propositions: mutation.mutation.propositions,
      clarifications: mutation.mutation.clarifications,
      turn_log: nextLog,
    };

    /* --- structural validation BEFORE commit ------------------------------ */
    const report = validateCaseState(nextState);
    if (!report.ok) {
      this.#diagnostics.record({
        kind: 'structural_validation_failed',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'Proposed case state failed structural validation; nothing was committed.',
        issues: report.issues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed.', false),
      };
    }

    const warnings = buildWarnings(mutation.mutation.accepted_proposition_ids.length, {
      opened: mutation.mutation.opened_clarification_ids.length,
      translated: turn.translation_indicated,
    });
    const response: StoredSubmitResponse = {
      case_version: effectiveVersion,
      turn_id: turnId,
      accepted_proposition_ids: mutation.mutation.accepted_proposition_ids,
      superseded_proposition_ids: mutation.mutation.superseded_proposition_ids,
      opened_clarification_ids: mutation.mutation.opened_clarification_ids,
      warnings,
    };
    const idempotency: IdempotencyRecord = {
      case_id: state.case_id,
      request_fingerprint: precheck.request_fingerprint,
      client_turn_id: request.client_turn_id,
      turn_id: turnId,
      recorded_at_ms: receivedAtMs,
      response,
    };

    let commit;
    try {
      commit = await this.#deps.store.commitTurn({
        case_id: state.case_id,
        expected_revision: stored.revision,
        next_state: nextState,
        idempotency,
      });
    } catch {
      // The store refused the write (a uniqueness rule it enforces itself).
      // Nothing was committed, and the safe reading is contention.
      return 'contended';
    }
    if (!commit.ok) return 'contended';

    return {
      kind: 'committed',
      turn_id: turnId,
      case: this.#project(commit.stored.state, warnings),
      recorded: resolveRecorded(
        commit.stored.state.propositions,
        response.accepted_proposition_ids,
      ),
      accepted_proposition_ids: [...response.accepted_proposition_ids],
      superseded_proposition_ids: [...response.superseded_proposition_ids],
      opened_clarification_ids: [...response.opened_clarification_ids],
      warnings,
    };
  }

  /* --------------------------------------------------------------------- */
  /* internals                                                              */
  /* --------------------------------------------------------------------- */

  #project(state: CaseState, warnings: string[] = []): CaseStateResponse {
    // Always the core projection. A second, hand-built agent-facing view is
    // how a forbidden slot eventually escapes.
    return projectCaseState(state, {
      review_url: this.#deps.reviewUrl(state.case_id),
      warnings,
    });
  }

  #ensureCompilerRegistered(): Promise<void> {
    // A failed registration is not cached: caching the rejected promise would
    // make one transient storage error permanent for the process.
    this.#compilerRegistered ??= this.#deps.store.compilerRegistry
      .register(this.#deps.compiler.registryEntry)
      .catch((error: unknown) => {
        this.#compilerRegistered = null;
        throw error;
      });
    return this.#compilerRegistered;
  }
}

/* ------------------------------------------------------------------------ */
/* Helpers                                                                   */
/* ------------------------------------------------------------------------ */

function principalOf(context: RuntimeRequestContext): string | null {
  const value = context.principal?.principal_id;
  return typeof value === 'string' && value.trim().length > 0 ? value : null;
}

function resolveRecorded(propositions: readonly Proposition[], ids: readonly string[]) {
  const byId = new Map(
    propositions.map((proposition) => [proposition.proposition_id, proposition]),
  );
  return ids
    .map((id) => byId.get(id))
    .filter((proposition): proposition is Proposition => proposition !== undefined)
    .map(interpretationSlot);
}

function wellFormedCommand(command: SubmitTurnCommand): boolean {
  if (typeof command.case_id !== 'string' || command.case_id.trim().length === 0) return false;
  if (!Array.isArray(command.in_reply_to)) return false;
  if (command.in_reply_to.some((value) => typeof value !== 'string' || value.length === 0)) {
    return false;
  }
  if (command.client_turn_id !== null && typeof command.client_turn_id !== 'string') return false;
  const payload: unknown = command.payload;
  if (typeof payload !== 'object' || payload === null) return false;
  const { context, answer } = payload as Partial<SourceTurnPayload>;
  if (!Array.isArray(context)) return false;
  if (context.some((message) => typeof message?.text !== 'string')) return false;
  return typeof answer?.text === 'string';
}

function buildWarnings(
  acceptedCount: number,
  facts: { opened: number; translated: boolean },
): string[] {
  const warnings: string[] = [];
  if (facts.opened > 0) {
    warnings.push('JuryAI needs a clarification before it can record an answer to that question.');
  } else if (acceptedCount === 0) {
    warnings.push('JuryAI did not record a canonical statement from that answer.');
  }
  if (facts.translated) {
    // Span fidelity is a claim about the material JuryAI received. A relay that
    // says it translated the answer has removed that claim's meaning, and the
    // record says so rather than quietly keeping the same standing.
    warnings.push(
      'That answer was relayed as a translation, so JuryAI cannot tie its wording to the words you used.',
    );
  }
  return warnings;
}
