/**
 * The JuryAI P2 case-formation runtime.
 *
 * This is the layer between a transport (WebMCP tools, first-party HTTP, file
 * import) and the canonical core. It is deliberately transport-independent:
 * it takes a trusted principal context that the transport has already
 * resolved, and returns canonical outcomes that a transport renames but never
 * reinterprets.
 *
 * The order of operations in `submitTurn` is the architecture, not an
 * implementation detail. In particular idempotency resolution happens BEFORE
 * version validation. "Have I already done this?" is logically prior to "is
 * this valid against current state?", and reversing them makes every
 * lost-response retry fail: the caller refreshes, retries with the new
 * version, and records the same statement twice.
 *
 * What this runtime does NOT do:
 *  - It does not register WebMCP tools.
 *  - It does not attest, lock, or expose attestation. Case formation only.
 *  - It does not let the semantic compiler write to canonical state.
 *  - It does not surface validator or compiler internals to a caller.
 */

import { deriveCaseStatus, projectCaseState, type CaseState } from '../core/attestation.js';
import {
  buildCompileRunRecord,
  buildCompilerInput,
  type CompileRunRecord,
  type CompilerOutput,
} from '../core/compiler-contract.js';
import {
  computeRequestFingerprint,
  DEFAULT_FINGERPRINT_REPLAY_WINDOW_MS,
  precheckSubmit,
  validateSubmitRequest,
  type IdempotencyRecord,
  type StoredSubmitResponse,
  type SubmitRequest,
} from '../core/idempotency.js';
import { livePropositions, type Proposition } from '../core/propositions.js';
import { validateCaseState } from '../core/structural-validator.js';
import {
  appendTurn,
  computePayloadCommitment,
  normalizePayload,
  validatePayloadShape,
  validateSourceTurnRecord,
  type SourceTurnPayload,
  type SourceTurnRecord,
} from '../core/turns.js';
import { canonicalSerialize, type CaseStateResponse, type SourceChannel } from '../core/types.js';
import type { CompilerRegistryEntry } from '../core/compiler-contract.js';
import type { SemanticCompilerPort } from './compiler-port.js';
import {
  isoFrom,
  type PayloadSaltFactory,
  type RuntimeClock,
  type RuntimeIdFactory,
} from './ids.js';
import {
  defaultRequirementSetProvider,
  type RequirementSetProvider,
} from './initial-requirements.js';
import { applyCompilerOutput } from './mutation-application.js';
import type { CaseCreateResult, CaseRuntimeStore, StoredCase } from './repositories.js';
import {
  failure,
  interpretationSlot,
  noopDiagnosticsSink,
  type RuntimeFailure,
  type GetCaseStateOutcome,
  type RuntimeDiagnosticsSink,
  type StartCaseOutcome,
  type SubmitTurnOutcome,
} from './results.js';

/* ------------------------------------------------------------------------ */
/* Trusted request context                                                   */
/* ------------------------------------------------------------------------ */

/**
 * The authenticated principal, resolved by the transport from a session. A
 * principal id appearing anywhere in external tool input is data, never
 * identity, and this runtime never reads one from a command.
 */
export interface RuntimePrincipal {
  principal_id: string;
}

export interface RuntimeRequestContext {
  principal: RuntimePrincipal;
  /**
   * Where the text reached JuryAI from. Resolved by the transport, never by
   * the caller: relayed input cannot promote itself to first-party
   * provenance by asking. Defaults to the relay channel.
   */
  source_channel?: SourceChannel;
  /** Relay's self-reported identity. Recorded for the record, never trusted. */
  relaying_agent?: string | null;
}

/**
 * The runtime's own start command. It intentionally mirrors, rather than
 * imports, the transport DTO: `client_request_id` is adapter-issued transport
 * metadata identifying the OPERATION, and the runtime owns what that means
 * without depending on the tools layer.
 */
export interface StartCaseCommand {
  client_request_id: string;
}

/**
 * Per-call execution context. Deliberately separate from the command: an
 * `AbortSignal` is how the caller is still listening, not something the case
 * records. Nothing here ever reaches canonical state.
 */
export interface RuntimeCallOptions {
  signal?: AbortSignal;
}

export interface GetCaseStateQuery {
  /** Omitted means "the authenticated principal's active draft". */
  case_id?: string;
}

export interface SubmitTurnCommand {
  case_id: string;
  expected_case_version: number;
  in_reply_to: string[];
  payload: SourceTurnPayload;
  /** Adapter-minted retry key. Never generated by a model. */
  client_turn_id: string | null;
  /** Self-reported by the relay. Recorded, never trusted. */
  source_language?: string | null;
  translation_indicated?: boolean;
}

/* ------------------------------------------------------------------------ */
/* Dependencies                                                              */
/* ------------------------------------------------------------------------ */

export interface DisclosureConfig {
  /** Trusted configuration. Never an external-AI-supplied value. */
  version: string;
}

export interface CaseRuntimeDependencies {
  store: CaseRuntimeStore;
  compiler: SemanticCompilerPort;
  clock: RuntimeClock;
  ids: RuntimeIdFactory;
  salts: PayloadSaltFactory;
  /**
   * First-party review entry point for a case. It is one way a human reaches
   * the draft, not the only one: independent first-party discovery of an
   * active draft is a separate product surface and must not depend on the
   * relay having kept this string.
   */
  reviewUrl: (caseId: string) => string;
  disclosure: DisclosureConfig;
  requirements?: RequirementSetProvider;
  diagnostics?: RuntimeDiagnosticsSink;
  fingerprintReplayWindowMs?: number;
  /** Bound on compare-and-swap retries under write contention. */
  maxCommitAttempts?: number;
}

const DEFAULT_MAX_COMMIT_ATTEMPTS = 3;

/**
 * A stale-case restart re-reads the case, after which the turn in question is
 * visible and the decision is determinate. One restart therefore suffices; the
 * bound only exists so a pathologically lagging replica cannot spin.
 */
const MAX_STALE_CASE_RESTARTS = 2;

/**
 * Why `#attemptSubmit` wants to be re-entered. Neither is an outcome: they say
 * the attempt could not decide yet, for two different reasons.
 */
type AttemptSignal = 'contended' | 'stale_case_restart';

export class CaseRuntime {
  readonly #deps: CaseRuntimeDependencies;
  readonly #requirements: RequirementSetProvider;
  readonly #diagnostics: RuntimeDiagnosticsSink;
  #compilerRegistered: Promise<CompilerRegistryEntry> | null = null;

  constructor(dependencies: CaseRuntimeDependencies) {
    this.#deps = dependencies;
    this.#requirements = dependencies.requirements ?? defaultRequirementSetProvider;
    this.#diagnostics = dependencies.diagnostics ?? noopDiagnosticsSink;
  }

  /* --------------------------------------------------------------------- */
  /* start_case                                                             */
  /* --------------------------------------------------------------------- */

  async startCase(
    context: RuntimeRequestContext,
    command: StartCaseCommand,
  ): Promise<StartCaseOutcome> {
    const principalId = principalOf(context);
    if (principalId === null) {
      return { kind: 'failed', failure: failure('AUTH_REQUIRED', 'No authenticated principal.') };
    }
    if (!isClientIssuedId(command?.client_request_id)) {
      return {
        kind: 'failed',
        failure: failure('INVALID_INPUT', 'A start request must carry a request id.'),
      };
    }

    // A retry of the same logical create replays its original result. Without
    // this, a lost create response comes back as OPEN_DRAFT_EXISTS — an error
    // describing the very draft the caller's own first attempt produced.
    const prior = await this.#guardedRead('start_request_lookup', null, () =>
      this.#deps.store.startRequests.findByRequest(principalId, command.client_request_id),
    );
    if (!prior.ok) {
      return { kind: 'failed', failure: unavailable('The case could not be created.') };
    }
    const priorRecord = prior.value;
    if (priorRecord !== null) {
      const replayed = await this.#guardedRead('case_by_start_request', priorRecord.case_id, () =>
        this.#deps.store.cases.findById(priorRecord.case_id),
      );
      if (!replayed.ok) {
        return { kind: 'failed', failure: unavailable('The case could not be created.') };
      }
      if (replayed.value && replayed.value.state.principal_id === principalId) {
        return { kind: 'created', replayed: true, case: this.#project(replayed.value.state) };
      }
      this.#diagnostics.record({
        kind: 'repository_unavailable',
        case_id: priorRecord.case_id,
        turn_id: null,
        compile_run_id: null,
        message: 'A start-request record names a case that cannot be read for this principal.',
        issues: [],
      });
      return { kind: 'failed', failure: unavailable('The case could not be created.') };
    }

    // There is deliberately NO active-draft read here. An observed draft cannot
    // be classified from this side: it may be the case this very request just
    // created, committed between the lookup above and the read below, in which
    // case answering OPEN_DRAFT_EXISTS would hand a caller a non-retryable
    // error for its own successful operation. Two ordinary reads are not one
    // snapshot, so `createCase` — which decides request identity and draft
    // uniqueness in the same atomic step — is the only authority allowed to
    // tell "my own case" from "somebody else's draft".

    const nowMs = this.#deps.clock.now();
    const state: CaseState = {
      case_id: this.#deps.ids.caseId(),
      case_version: 0,
      principal_id: principalId,
      // Recorded at creation and never backfillable: a disclosure accepted
      // after the fact is not a disclosure.
      disclosure_version: this.#deps.disclosure.version,
      disclosure_accepted_at: isoFrom(nowMs),
      requirements: this.#requirements.initialRequirements(),
      propositions: [],
      clarifications: [],
      evidence_references: [],
      turn_log: [],
      attestations: [],
    };

    const report = validateCaseState(state);
    if (!report.ok) {
      this.#diagnostics.record({
        kind: 'structural_validation_failed',
        case_id: state.case_id,
        turn_id: null,
        compile_run_id: null,
        message: 'Initial case state failed structural validation.',
        issues: report.issues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'The case could not be created.', true),
      };
    }

    let result: CaseCreateResult;
    try {
      // Case and start-request record commit together, or not at all.
      result = await this.#deps.store.createCase({
        state,
        idempotency: {
          principal_id: principalId,
          client_request_id: command.client_request_id,
          case_id: state.case_id,
          recorded_at_ms: nowMs,
        },
      });
    } catch (error) {
      this.#diagnostics.record({
        kind: 'case_creation_failed',
        case_id: state.case_id,
        turn_id: null,
        compile_run_id: null,
        message: error instanceof Error ? error.message : 'Case creation failed.',
        issues: [],
      });
      return { kind: 'failed', failure: unavailable('The case could not be created.') };
    }

    if (result.ok) {
      return { kind: 'created', replayed: false, case: this.#project(result.stored.state) };
    }
    if (result.stored === null) {
      return { kind: 'failed', failure: unavailable('The case could not be created.') };
    }
    // The atomic decision. The same request id means the winner IS this
    // operation, so it replays as created; a different one means the principal
    // already has a draft, which is the only route to OPEN_DRAFT_EXISTS. Never
    // a silent resume: an agent that starts a case while another request's
    // draft is open must be told, or a second conversation quietly overwrites
    // the first.
    return result.reason === 'start_request_replayed'
      ? { kind: 'created', replayed: true, case: this.#project(result.stored.state) }
      : { kind: 'open_draft_exists', case: this.#project(result.stored.state) };
  }

  /* --------------------------------------------------------------------- */
  /* get_case_state                                                         */
  /* --------------------------------------------------------------------- */

  async getCaseState(
    context: RuntimeRequestContext,
    query: GetCaseStateQuery = {},
  ): Promise<GetCaseStateOutcome> {
    const principalId = principalOf(context);
    if (principalId === null) {
      return { kind: 'failed', failure: failure('AUTH_REQUIRED', 'No authenticated principal.') };
    }

    const read = await this.#guardedRead('case_read', query.case_id ?? null, () =>
      query.case_id === undefined
        ? this.#deps.store.cases.findActiveDraftByPrincipal(principalId)
        : this.#deps.store.cases.findById(query.case_id),
    );
    // A storage failure is not "no such case": telling the caller its case is
    // gone when the database merely blinked is both wrong and unrecoverable.
    if (!read.ok) {
      return { kind: 'failed', failure: unavailable('The case could not be read.') };
    }

    // A foreign case is reported as not found rather than as forbidden: the
    // distinction is an existence oracle over other people's case ids.
    const stored = read.value;
    if (!stored || stored.state.principal_id !== principalId) {
      return { kind: 'failed', failure: failure('CASE_NOT_FOUND', 'No such case.') };
    }
    return { kind: 'ok', case: this.#project(stored.state) };
  }

  /* --------------------------------------------------------------------- */
  /* submit_turn                                                            */
  /* --------------------------------------------------------------------- */

  /**
   * Returns a `SubmitTurnOutcome` for every outcome the case can have,
   * including every failure. The single exception is cancellation: if the
   * caller's own signal aborts, that abort is rethrown rather than flattened
   * into a failure, so the transport's execution and retry path can unwind
   * instead of treating a cancelled request as a processing error.
   */
  async submitTurn(
    context: RuntimeRequestContext,
    command: SubmitTurnCommand,
    options: RuntimeCallOptions = {},
  ): Promise<SubmitTurnOutcome> {
    // An already-cancelled call does no work at all: no state read, no
    // compiler execution, no commit.
    options.signal?.throwIfAborted();

    const principalId = principalOf(context);
    if (principalId === null) {
      return { kind: 'failed', failure: failure('AUTH_REQUIRED', 'No authenticated principal.') };
    }

    if (!wellFormedCommand(command)) {
      return {
        kind: 'failed',
        failure: failure('INVALID_INPUT', 'The submission is not well formed.'),
      };
    }

    const payload = normalizePayload(command.payload);
    const payloadIssues = validatePayloadShape(payload, 'payload');
    if (payloadIssues.length > 0) {
      return {
        kind: 'failed',
        failure: failure('INVALID_INPUT', 'The relayed turn payload is not well formed.'),
      };
    }
    const inReplyTo = [...new Set(command.in_reply_to)].sort();
    const request: SubmitRequest = {
      case_id: command.case_id,
      principal_id: principalId,
      expected_case_version: command.expected_case_version,
      in_reply_to: inReplyTo,
      payload,
      client_turn_id: command.client_turn_id,
    };
    const requestIssues = validateSubmitRequest(request, 'submit');
    if (requestIssues.length > 0) {
      return {
        kind: 'failed',
        failure: failure('INVALID_INPUT', 'The submission is not well formed.'),
      };
    }

    const attempts = this.#deps.maxCommitAttempts ?? DEFAULT_MAX_COMMIT_ATTEMPTS;
    const relayClaims: RelayClaims = {
      // Self-reported by the relay and recorded as such. A translated answer
      // has no span fidelity to anything the human actually typed, so the
      // claim is stored rather than quietly dropped.
      source_language: command.source_language ?? null,
      translation_indicated: command.translation_indicated === true,
    };

    // Two distinct reasons to re-enter, budgeted separately. Contention means
    // somebody else committed first; a stale-case restart means this attempt
    // read the case before a turn it needed to see, and the re-read resolves
    // that for good.
    let contended = 0;
    let restarts = 0;
    for (;;) {
      const outcome = await this.#attemptSubmit(
        context,
        principalId,
        request,
        relayClaims,
        options,
      );
      if (outcome === 'contended') {
        contended += 1;
        if (contended >= attempts) break;
        continue;
      }
      if (outcome === 'stale_case_restart') {
        restarts += 1;
        if (restarts > MAX_STALE_CASE_RESTARTS) break;
        continue;
      }
      return outcome;
    }

    this.#diagnostics.record({
      kind: contended > 0 ? 'commit_contention_exhausted' : 'stale_case_restarts_exhausted',
      case_id: request.case_id,
      turn_id: null,
      compile_run_id: null,
      message:
        contended > 0
          ? 'Exhausted compare-and-swap attempts under write contention.'
          : 'Repeated stale case reads prevented a decision about this submission.',
      issues: [],
    });
    return {
      kind: 'failed',
      failure: failure('INTERNAL_ERROR', 'The case is busy. Try again.', true),
    };
  }

  /**
   * One full pass of the pipeline against a freshly read case. Returns
   * `'contended'` when the compare-and-swap lost, so the caller re-reads and
   * re-runs from the top: a mutation prepared against superseded state is
   * never rewritten onto the winner.
   */
  async #attemptSubmit(
    context: RuntimeRequestContext,
    principalId: string,
    request: SubmitRequest,
    relayClaims: RelayClaims,
    options: RuntimeCallOptions,
  ): Promise<SubmitTurnOutcome | AttemptSignal> {
    const read = await this.#guardedRead('case_read', request.case_id, () =>
      this.#deps.store.cases.findById(request.case_id),
    );
    if (!read.ok) {
      return { kind: 'failed', failure: unavailable('That answer could not be processed.') };
    }
    const stored = read.value;
    if (!stored || stored.state.principal_id !== principalId) {
      return { kind: 'failed', failure: failure('CASE_NOT_FOUND', 'No such case.') };
    }
    const state = stored.state;

    /* --- idempotency first, then the lock, then CAS. --------------------- */
    const idempotencyRead = await this.#guardedRead('idempotency_read', request.case_id, () =>
      this.#deps.store.idempotency.listByCase(request.case_id),
    );
    // Proceeding without the replay store would turn a lost-response retry
    // into a duplicate write, which is the one failure this store prevents.
    if (!idempotencyRead.ok) {
      return { kind: 'failed', failure: unavailable('That answer could not be processed.') };
    }
    // Provenance is part of source-event identity, not decoration. Two
    // submissions carrying the same words for the same requirements through
    // different channels — relayed vs first-party, a different relaying agent,
    // a translation vs the user's own wording — are separate source events and
    // both belong in the immutable log; collapsing them would drop one from the
    // audit trail and answer it with the other's provenance and warnings.
    //
    // The core fingerprint is frozen and hashes content only, so provenance is
    // applied as a CONJUNCT rather than by extending that hash: a heuristic
    // match must agree on content AND provenance. Implemented by narrowing the
    // store handed to `precheckSubmit`, so core still owns the ordering, the
    // replay window, the CAS and the conflict shape.
    // Core's content fingerprint, computed once. Both the conflict hint and the
    // read-consistency guard below need it; neither reimplements its rules.
    const contentFingerprint = computeRequestFingerprint({
      principal_id: request.principal_id,
      case_id: request.case_id,
      in_reply_to: request.in_reply_to,
      payload: request.payload,
    });
    const requestProvenance = provenanceKey({
      source_channel: context.source_channel ?? 'webmcp_agent_relay',
      relaying_agent: context.relaying_agent ?? null,
      source_language: relayClaims.source_language,
      translation_indicated: relayClaims.translation_indicated,
    });
    const eligible = idempotencyRead.value.filter((record) =>
      sharesSourceIdentity(record, request, requestProvenance, state),
    );

    // One timestamp for the whole attempt: replay-window arithmetic in the
    // precheck and in the read-consistency guard below must agree about "now".
    const decidedAtMs = this.#deps.clock.now();
    const precheck = precheckSubmit(request, {
      store: eligible,
      log: state.turn_log,
      current_case_version: state.case_version,
      now_ms: decidedAtMs,
      window_ms: this.#deps.fingerprintReplayWindowMs,
    });

    if (precheck.kind === 'replay') {
      const previous = precheck.record.response;

      // The case above was read BEFORE the idempotency record that proves the
      // original write committed. Those two reads are not one snapshot under
      // ordinary read-committed storage, so a duplicate can hold a pre-commit
      // case while matching a post-commit replay record — and would then
      // describe a committed result using a version and proposition set that
      // predate it: accepted ids from the record, `case_version` and
      // `recorded` from before those propositions existed. Re-read, so the
      // replay is built from state at least as fresh as the record it matched.
      const refreshed = await this.#guardedRead('replay_case_refresh', request.case_id, () =>
        this.#deps.store.cases.findById(request.case_id),
      );
      if (!refreshed.ok) {
        return { kind: 'failed', failure: unavailable('That answer could not be processed.') };
      }

      // Everything below is an INCONSISTENCY, never a missing case. By this
      // point this attempt has already read the case, authorised the principal
      // against it, and matched a durable record proving the write committed.
      // A refresh that now returns nothing, or a different owner for an
      // immutable field, means the reads disagree — a lagging replica, most
      // likely. Answering CASE_NOT_FOUND would be non-retryable, so the
      // transport would stop and a committed lost-response retry would become
      // permanently unrecoverable. Fail closed, retryably, and say why
      // internally.
      const inconsistent = (reason: string): SubmitTurnOutcome => {
        this.#diagnostics.record({
          kind: 'replay_state_inconsistent',
          case_id: request.case_id,
          turn_id: previous.turn_id,
          compile_run_id: null,
          message: 'Replay refresh disagrees with the durable replay record: ' + reason,
          issues: [],
        });
        return { kind: 'failed', failure: unavailable('That answer could not be processed.') };
      };

      if (!refreshed.value) {
        return inconsistent('the refreshed read returned no case.');
      }
      if (refreshed.value.state.principal_id !== principalId) {
        return inconsistent('the refreshed case reports a different principal.');
      }

      const replayState = refreshed.value.state;

      // The initial filter had to leave this record eligible when its turn was
      // not visible in the stale read: excluding on uncertainty would turn a
      // lost-response retry into a duplicate write. Now the turn IS visible,
      // so the uncertainty is gone — and a different provenance key means this
      // was never the same source event. Only the heuristic path is rechecked;
      // an exact client_turn_id is operation identity and outranks content.
      const replayedTurn = replayState.turn_log.find((turn) => turn.turn_id === previous.turn_id);
      if (
        precheck.match === 'fingerprint' &&
        replayedTurn !== undefined &&
        provenanceKey(replayedTurn) !== requestProvenance
      ) {
        // Not a replay, and not an error either. Re-run the decision against
        // the refreshed case, where the turn is visible and the filter will
        // correctly exclude it, so this submission gets whatever outcome it
        // actually deserves: proceed, version conflict, locked, or invalid.
        return 'stale_case_restart';
      }

      const recorded = resolveRecorded(replayState.propositions, previous.accepted_proposition_ids);

      // The refreshed case must also be able to support the result the record
      // claims. A partial replay would describe an outcome that does not
      // exist, and inventing the missing entries would describe one that
      // never did.
      const turnPresent = replayedTurn !== undefined;
      if (turnPresent === false || recorded.length !== previous.accepted_proposition_ids.length) {
        return inconsistent(
          'turn present=' +
            String(turnPresent) +
            ', propositions resolved=' +
            String(recorded.length) +
            '/' +
            String(previous.accepted_proposition_ids.length) +
            '.',
        );
      }

      return {
        kind: 'replayed',
        match: precheck.match,
        recorded_at_case_version: previous.case_version,
        turn_id: previous.turn_id,
        case: this.#project(replayState, previous.warnings),
        recorded,
        accepted_proposition_ids: [...previous.accepted_proposition_ids],
        superseded_proposition_ids: [...previous.superseded_proposition_ids],
        opened_clarification_ids: [...previous.opened_clarification_ids],
        warnings: [...previous.warnings],
      };
    }

    // The mirror of the stale-case race. There the case read lagged the
    // idempotency read, and the replay refresh fixed it. Here the case read is
    // AHEAD: it already contains the turn whose replay record the idempotency
    // read has not caught up to. Nothing downstream would notice — a previous
    // turn that recorded nothing canonical leaves `case_version` untouched, so
    // the CAS passes and this regenerated retry would commit a second source
    // turn and compile run for one source event.
    //
    // Two independently read repositories are not one snapshot, in either
    // direction, and the runtime must never make a duplicate-write decision by
    // assuming they are. If the case can show a turn that already carries this
    // request's replay identity but the replay store cannot show its record,
    // the stores disagree: stop, and let the caller retry once they converge.
    //
    // This is idempotency resolution, not fresh-write validation, so it runs
    // ahead of CASE_LOCKED, VERSION_CONFLICT and requirement validation. All
    // three answer "this new write is not allowed"; none of them is true of a
    // request that may already have committed. CASE_LOCKED in particular is
    // non-retryable, so answering it here would tell a caller to stop retrying
    // an operation that had in fact succeeded.
    const inconsistentTurn = replayIdentityTurnMissingRecord({
      state,
      records: idempotencyRead.value,
      request,
      requestProvenance,
      contentFingerprint,
      now_ms: decidedAtMs,
      window_ms: this.#deps.fingerprintReplayWindowMs ?? DEFAULT_FINGERPRINT_REPLAY_WINDOW_MS,
    });
    if (inconsistentTurn) {
      this.#diagnostics.record({
        kind: 'replay_store_inconsistent',
        case_id: state.case_id,
        turn_id: inconsistentTurn.turn_id,
        compile_run_id: null,
        message:
          "The case already contains a turn carrying this request's replay identity, but the " +
          'replay store read does not contain its record; the two reads disagree in freshness.',
        issues: [],
      });
      return { kind: 'failed', failure: unavailable('That answer could not be processed.') };
    }

    // Only a genuinely NEW write is refused by the lock. An operation that
    // already happened stays replayable for the lifetime of the case: the
    // caller that lost a response is asking what its earlier write did, and
    // a later attestation does not unmake it. This check sits ahead of the
    // version conflict deliberately — telling a caller its version is stale
    // invites a refresh-and-retry against a case that can never accept it.
    if (deriveCaseStatus(state) === 'locked') {
      return {
        kind: 'failed',
        failure: failure('CASE_LOCKED', 'This case version has been attested and cannot change.'),
      };
    }

    if (precheck.kind === 'version_conflict') {
      // `recent_turns` stays exactly as core built it — the complete recent
      // same-principal history, unfiltered. That list is what lets a caller
      // compare its own payload rather than infer, and hiding turns from it
      // would make a lost write harder to recognise, not easier.
      //
      // `likely_already_recorded` is a different claim: "your write probably
      // landed". Core computes it from the content-only fingerprint, so a
      // distinct source event with the same words would be told it had already
      // been recorded — and a caller that believes it may suppress the retry,
      // losing the event from the immutable log. Recomputed here with the same
      // provenance conjunct that governs heuristic replay.
      const likelyAlreadyRecorded = state.turn_log.some(
        (turn) =>
          turn.case_id === request.case_id &&
          turn.principal_id === request.principal_id &&
          turn.request_fingerprint === contentFingerprint &&
          provenanceKey(turn) === requestProvenance,
      );
      return {
        kind: 'version_conflict',
        current_case_version: precheck.current_case_version,
        recent_turns: precheck.recent_turns,
        likely_already_recorded: likelyAlreadyRecorded,
        case: this.#project(state),
      };
    }

    // Whether a requirement reference is valid is already decided by the case
    // we loaded. Answering it before touching the registry keeps a malformed
    // request deterministic: the same input must not return INVALID_INPUT when
    // storage is healthy and a retryable INTERNAL_ERROR when it is not. It
    // also avoids a persistent registration side effect for a request that can
    // never proceed. This sits AFTER replay, lock and version conflict: a
    // committed operation stays replayable from durable history even if the
    // same request would fail present-day validation.
    const known = new Set(state.requirements.map((definition) => definition.requirement_id));
    if (request.in_reply_to.some((requirementId) => !known.has(requirementId))) {
      return {
        kind: 'failed',
        failure: failure(
          'INVALID_INPUT',
          'The turn answers a requirement this case does not have.',
        ),
      };
    }

    // Only a fresh write needs a compiler, so registration happens here rather
    // than at entry. A replay, a locked case and a stale write are all decided
    // from durable state alone; making them depend on the registry means a
    // registry outage can hide an already-committed result from the caller
    // that is asking what happened to it.
    let pinnedCompiler: CompilerRegistryEntry;
    try {
      pinnedCompiler = await this.#ensureCompilerRegistered();
    } catch (error) {
      this.#diagnostics.record({
        kind: 'repository_unavailable',
        case_id: state.case_id,
        turn_id: null,
        compile_run_id: null,
        message:
          'compiler_registry_register: ' +
          (error instanceof Error ? error.message : 'unknown error'),
        issues: [],
      });
      return { kind: 'failed', failure: unavailable('That answer could not be processed.') };
    }

    /* --- immutable source turn ------------------------------------------- */
    const compileRunId = this.#deps.ids.compileRunId();
    const turnId = this.#deps.ids.turnId();
    const salt = this.#deps.salts.next();
    const receivedAtMs = this.#deps.clock.now();
    const turn: SourceTurnRecord = {
      turn_id: turnId,
      case_id: state.case_id,
      case_version_before: state.case_version,
      received_at: isoFrom(receivedAtMs),
      principal_id: principalId,
      source_channel: context.source_channel ?? 'webmcp_agent_relay',
      relaying_agent: context.relaying_agent ?? null,
      source_language: relayClaims.source_language,
      translation_indicated: relayClaims.translation_indicated,
      in_reply_to: [...request.in_reply_to],
      client_turn_id: request.client_turn_id,
      request_fingerprint: precheck.request_fingerprint,
      payload: request.payload,
      payload_commitment_salt: salt,
      payload_commitment: computePayloadCommitment(request.payload, salt),
      compile_run_id: compileRunId,
    };

    const turnIssues = validateSourceTurnRecord(turn, 'turn');
    if (turnIssues.length > 0) {
      this.#diagnostics.record({
        kind: 'source_turn_invalid',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'Constructed source turn failed its own contract.',
        issues: turnIssues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'The turn could not be recorded.', true),
      };
    }

    let nextLog: SourceTurnRecord[];
    try {
      nextLog = appendTurn(state.turn_log, turn);
    } catch {
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'The turn could not be recorded.', true),
      };
    }

    /* --- semantic compilation -------------------------------------------- */
    const compilerInput = buildCompilerInput({
      compile_run_id: compileRunId,
      // The PINNED snapshot, never the adapter's live object. The adapter owns
      // `registryEntry` and may mutate it after registration; a run citing a
      // mutated version id would name an artefact the registry never received,
      // and every proposition it produced would claim an unregistered compiler.
      compiler_version_id: pinnedCompiler.compiler_version_id,
      state: { case_id: state.case_id, case_version: state.case_version },
      turn,
      requirements: state.requirements,
      livePropositions: livePropositions(state.propositions),
    });

    // Re-checked here as well as at entry: the compare-and-swap retry loop can
    // re-enter this method, and a cancelled call must not start a second
    // expensive execution.
    options.signal?.throwIfAborted();

    const startedAt = isoFrom(this.#deps.clock.now());
    let output: CompilerOutput;
    try {
      // The adapter gets a DETACHED copy. `buildCompilerInput` builds fresh
      // arrays but still holds the runtime's own requirement, proposition and
      // turn objects; an adapter that writes through them would edit canonical
      // state on its way past, and a `no_assertions` verdict would then commit
      // a mutation nothing proposed. The runtime keeps `compilerInput`
      // untouched for validation, the run record and the input hash.
      output = await this.#deps.compiler.compile(structuredClone(compilerInput), {
        signal: options.signal,
      });
    } catch (error) {
      // A cancelled execution is not a failed one. Flattening it into
      // INTERNAL_ERROR would tell the transport to consider retrying work the
      // caller has already walked away from.
      if (options.signal?.aborted === true) {
        // `signal.reason` and nothing else. A caller that called `abort(null)`
        // chose null as its reason, and `?? error` would silently hand back the
        // adapter's rejection instead — reporting a compiler failure for an
        // operation the caller cancelled.
        throw options.signal.reason;
      }
      this.#diagnostics.record({
        kind: 'compiler_threw',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: error instanceof Error ? error.message : 'Compiler failed.',
        issues: [],
      });
      // Nothing is committed: no turn, no run, no version movement. A retry
      // carrying the same client_turn_id is therefore still a fresh request.
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed. Try again.', true),
      };
    }
    const finishedAt = isoFrom(this.#deps.clock.now());

    // Cancellation is re-checked HERE, before anything is persisted. Passing
    // the signal to the adapter is advisory: an adapter may ignore it, may
    // fail to abort its provider request, or may simply win the race and
    // resolve a moment after the caller walked away. Without this check the
    // runtime would hand the caller an abort while still committing the very
    // submission it says was cancelled. Everything after this line writes.
    options.signal?.throwIfAborted();

    /* --- fix the compiler's output at the runtime boundary ---------------- */
    // Everything above this line is ours; `output` is the first object in the
    // pipeline produced outside the runtime. A provider adapter that returns a
    // structurally malformed value makes the core contract check dereference
    // fields that are not there, and an exception thrown here would escape
    // `submitTurn` instead of becoming a runtime failure. The boundary is
    // enforced here rather than by loosening the frozen core validator.
    let runRecord: CompileRunRecord;
    try {
      runRecord = buildCompileRunRecord(compilerInput, output, {
        started_at: startedAt,
        finished_at: finishedAt,
      });
    } catch (error) {
      this.#diagnostics.record({
        kind: 'compiler_contract_violation',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message:
          'Compiler output was too malformed to record as a compile run: ' +
          (error instanceof Error ? error.message : 'unknown error'),
        issues: [],
      });
      // No run record can be built, so none is persisted; the failure lives in
      // the diagnostics sink. Nothing is committed, so the retry key is fresh.
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed.', false),
      };
    }
    // Append-only audit, written whether or not the result is absorbed. A run
    // that happened and was rejected is history; hiding it makes "the compiler
    // never proposed X" indistinguishable from "the runtime refused X".
    //
    // This also holds when the caller aborts while this append is in flight:
    // the compiler really did execute, so the record stands. Deleting it to
    // make a cancellation look tidier would falsify the audit trail. What
    // cancellation must prevent is the CANONICAL commit below, not the history
    // of what already ran.
    try {
      await this.#deps.store.compileRuns.append(runRecord);
    } catch (error) {
      // The caller may have aborted while this append was in flight, and the
      // append may then have failed for its own reasons. Cancellation wins:
      // reporting a storage failure would tell the caller its submission broke
      // when in fact the caller withdrew it, and `retryable: true` would invite
      // it to send again.
      if (options.signal?.aborted === true) {
        throw options.signal.reason;
      }
      this.#diagnostics.record({
        kind: 'repository_unavailable',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message:
          'compile_run_append: ' + (error instanceof Error ? error.message : 'unknown error'),
        issues: [],
      });
      return { kind: 'failed', failure: unavailable('That answer could not be processed.') };
    }

    // From here on `runRecord.output` is the authoritative compiler output.
    // The adapter-owned `output` object is not read again.
    // Last safe boundary, placed immediately after the append and BEFORE the
    // recorded output is inspected. The append is the final await before the
    // commit, and everything between here and `commitTurn` is synchronous, so
    // one check covers the whole window — but only from here. Below this line
    // sit the contract, mutation and structural-validation early returns, and
    // reaching one of those first would answer a cancelled caller with
    // INTERNAL_ERROR instead of its own cancellation. A caller that has walked
    // away is not owed a verdict on the compiler's output.
    //
    // The signal deliberately stops HERE and is not handed to `commitTurn`.
    // Once an atomic canonical commit has started, interrupting it would trade
    // a clean cancellation for an indeterminate half-written case, which is
    // strictly worse than honouring a commit the caller no longer wants. Any
    // asynchronous step added between this point and the commit needs the same
    // arbitration after it.
    options.signal?.throwIfAborted();

    if (runRecord.contract_issues.length > 0) {
      this.#diagnostics.record({
        kind: 'compiler_contract_violation',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'Compiler output violated the core contract.',
        issues: runRecord.contract_issues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed.', false),
      };
    }

    /* --- server-owned mutation ------------------------------------------- */
    const nextVersion = state.case_version + 1;
    const mutation = applyCompilerOutput({
      state,
      turn,
      // The AUDITED snapshot, never the adapter's object. `output` is still
      // owned by the adapter, which may hold a reference and mutate it while
      // the append above is awaited — leaving a compile-run record that does
      // not describe the output canonical state was actually built from. One
      // immutable value drives contract validation, persistence and mutation.
      output: runRecord.output,
      next_case_version: nextVersion,
      ids: this.#deps.ids,
    });
    if (!mutation.ok) {
      this.#diagnostics.record({
        kind: 'mutation_rejected',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'Compiler output could not be applied to canonical state.',
        issues: mutation.issues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed.', false),
      };
    }

    // The canonical version moves only when the canonical projection moves.
    // Appending a turn that produced nothing canonical is log growth, not a
    // new version of the case.
    const effectiveVersion = mutation.mutation.changed ? nextVersion : state.case_version;
    const nextState: CaseState = {
      ...state,
      case_version: effectiveVersion,
      propositions: mutation.mutation.propositions,
      clarifications: mutation.mutation.clarifications,
      turn_log: nextLog,
    };

    /* --- structural validation BEFORE commit ------------------------------ */
    const report = validateCaseState(nextState);
    if (!report.ok) {
      this.#diagnostics.record({
        kind: 'structural_validation_failed',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'Proposed case state failed structural validation; nothing was committed.',
        issues: report.issues,
      });
      return {
        kind: 'failed',
        failure: failure('INTERNAL_ERROR', 'That answer could not be processed.', false),
      };
    }

    const warnings = buildWarnings(mutation.mutation.accepted_proposition_ids.length, {
      opened: mutation.mutation.opened_clarification_ids.length,
      translated: turn.translation_indicated,
    });
    const response: StoredSubmitResponse = {
      case_version: effectiveVersion,
      turn_id: turnId,
      accepted_proposition_ids: mutation.mutation.accepted_proposition_ids,
      superseded_proposition_ids: mutation.mutation.superseded_proposition_ids,
      opened_clarification_ids: mutation.mutation.opened_clarification_ids,
      warnings,
    };
    const idempotency: IdempotencyRecord = {
      case_id: state.case_id,
      request_fingerprint: precheck.request_fingerprint,
      client_turn_id: request.client_turn_id,
      turn_id: turnId,
      recorded_at_ms: receivedAtMs,
      response,
    };

    let commit;
    try {
      commit = await this.#deps.store.commitTurn({
        case_id: state.case_id,
        expected_revision: stored.revision,
        next_state: nextState,
        idempotency,
      });
    } catch (error) {
      // A THROW is the store failing, not the store declining: contention is
      // modelled as a result. Retrying the pipeline here would recompile
      // against the same failure and bill another compile run for it.
      this.#diagnostics.record({
        kind: 'repository_unavailable',
        case_id: state.case_id,
        turn_id: turnId,
        compile_run_id: compileRunId,
        message: 'commit_turn: ' + (error instanceof Error ? error.message : 'unknown error'),
        issues: [],
      });
      return { kind: 'failed', failure: unavailable('That answer could not be processed.') };
    }
    if (!commit.ok) return 'contended';

    return {
      kind: 'committed',
      turn_id: turnId,
      case: this.#project(commit.stored.state, warnings),
      recorded: resolveRecorded(
        commit.stored.state.propositions,
        response.accepted_proposition_ids,
      ),
      accepted_proposition_ids: [...response.accepted_proposition_ids],
      superseded_proposition_ids: [...response.superseded_proposition_ids],
      opened_clarification_ids: [...response.opened_clarification_ids],
      warnings,
    };
  }

  /* --------------------------------------------------------------------- */
  /* internals                                                              */
  /* --------------------------------------------------------------------- */

  #project(state: CaseState, warnings: string[] = []): CaseStateResponse {
    // Always the core projection. A second, hand-built agent-facing view is
    // how a forbidden slot eventually escapes.
    return projectCaseState(state, {
      review_url: this.#deps.reviewUrl(state.case_id),
      warnings,
    });
  }

  /**
   * Repository reads reject in production. Cancellation is the one intentional
   * rejection this runtime propagates; a database blinking is not that, and
   * must become a `RuntimeFailure` the transport can act on.
   */
  async #guardedRead<T>(
    operation: string,
    caseId: string | null,
    read: () => Promise<T>,
  ): Promise<{ ok: true; value: T } | { ok: false }> {
    try {
      return { ok: true, value: await read() };
    } catch (error) {
      this.#diagnostics.record({
        kind: 'repository_unavailable',
        case_id: caseId,
        turn_id: null,
        compile_run_id: null,
        message: operation + ': ' + (error instanceof Error ? error.message : 'unknown error'),
        issues: [],
      });
      return { ok: false };
    }
  }

  /**
   * Registers the compiler artefact once and returns the snapshot that was
   * registered. Everything downstream cites THAT, not `compiler.registryEntry`:
   * the adapter owns its entry object and may mutate it afterwards, and a
   * compile run naming a version id the registry never received cannot be
   * reproduced — which is the entire point of storing the artefact.
   */
  #ensureCompilerRegistered(): Promise<CompilerRegistryEntry> {
    // A failed registration is not cached: caching the rejected promise would
    // make one transient storage error permanent for the process.
    this.#compilerRegistered ??= (async () => {
      const pinned = structuredClone(this.#deps.compiler.registryEntry);
      await this.#deps.store.compilerRegistry.register(pinned);
      return pinned;
    })().catch((error: unknown) => {
      this.#compilerRegistered = null;
      throw error;
    });
    return this.#compilerRegistered;
  }
}

/* ------------------------------------------------------------------------ */
/* Helpers                                                                   */
/* ------------------------------------------------------------------------ */

/**
 * A turn already in the case that carries this request's replay identity, but
 * whose idempotency record is absent from the replay-store read.
 *
 * Identity follows the same hierarchy used everywhere else:
 *  - an exact, non-null `client_turn_id` is operation identity and qualifies
 *    regardless of the heuristic window;
 *  - otherwise content fingerprint AND provenance must agree, and the turn must
 *    fall inside the heuristic replay window. The window is measured from the
 *    turn's server receipt time, since the record that would normally carry
 *    `recorded_at_ms` is exactly what is missing.
 *
 * Old same-content statements outside the window are therefore NOT flagged:
 * they are ordinary history, and treating them as inconsistency would block a
 * legitimate later submission forever.
 */
function replayIdentityTurnMissingRecord(args: {
  state: CaseState;
  records: readonly IdempotencyRecord[];
  request: SubmitRequest;
  requestProvenance: string;
  contentFingerprint: string;
  now_ms: number;
  window_ms: number;
}): SourceTurnRecord | undefined {
  const recorded = new Set(args.records.map((record) => record.turn_id));
  return args.state.turn_log.find((turn) => {
    if (turn.principal_id !== args.request.principal_id) return false;
    if (recorded.has(turn.turn_id)) return false;
    if (
      args.request.client_turn_id !== null &&
      turn.client_turn_id === args.request.client_turn_id
    ) {
      return true;
    }
    if (turn.request_fingerprint !== args.contentFingerprint) return false;
    if (provenanceKey(turn) !== args.requestProvenance) return false;
    const receivedMs = Date.parse(turn.received_at);
    return Number.isFinite(receivedMs) && args.now_ms - receivedMs <= args.window_ms;
  });
}

/**
 * May a stored replay record stand in for THIS request?
 *
 * An exact `client_turn_id` is network-operation identity and outranks every
 * content heuristic: a caller retrying the same id replays even if transport
 * metadata drifted between attempts. Only the heuristic fingerprint path is
 * narrowed by provenance.
 */
function sharesSourceIdentity(
  record: IdempotencyRecord,
  request: SubmitRequest,
  requestProvenance: string,
  state: CaseState,
): boolean {
  if (request.client_turn_id !== null && record.client_turn_id === request.client_turn_id) {
    return true;
  }
  const turn = state.turn_log.find((entry) => entry.turn_id === record.turn_id);
  // The record's turn is not in the case we loaded — the stale-read race the
  // replay refresh exists for. We cannot show the provenance differs, and
  // excluding on uncertainty would turn a lost-response retry into a duplicate
  // write, so the record stays eligible. The refresh re-checks provenance once
  // the turn becomes visible, and restarts the attempt if it does not match.
  if (!turn) return true;
  return provenanceKey(turn) === requestProvenance;
}

/**
 * An adapter-issued operation id. One rule for `client_request_id` and
 * `client_turn_id` so the two cannot drift: a non-empty string with at least
 * one non-whitespace character. The value is validated, never normalised — the
 * id is stored exactly as the adapter sent it, because exact identity is the
 * whole point of it.
 */
function isClientIssuedId(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0;
}

/** Relay self-reports carried alongside a submission. Recorded, never trusted. */
interface RelayClaims {
  source_language: string | null;
  translation_indicated: boolean;
}

/**
 * Canonical identity of where a submission came from. `null` and absent
 * collapse to the same value, so an adapter that omits a field and one that
 * sends it as null describe the same source event rather than two.
 */
function provenanceKey(source: {
  source_channel: SourceChannel;
  relaying_agent: string | null;
  source_language: string | null;
  translation_indicated: boolean;
}): string {
  return canonicalSerialize({
    source_channel: source.source_channel,
    relaying_agent: source.relaying_agent ?? null,
    source_language: source.source_language ?? null,
    translation_indicated: source.translation_indicated === true,
  });
}

/**
 * A storage failure is opaque to the caller and retryable. Table names, driver
 * text and stack detail go to the diagnostics sink, never across the boundary.
 */
function unavailable(message: string): RuntimeFailure {
  return failure('INTERNAL_ERROR', message + ' Try again.', true);
}

function principalOf(context: RuntimeRequestContext): string | null {
  const value = context.principal?.principal_id;
  return typeof value === 'string' && value.trim().length > 0 ? value : null;
}

function resolveRecorded(propositions: readonly Proposition[], ids: readonly string[]) {
  const byId = new Map(
    propositions.map((proposition) => [proposition.proposition_id, proposition]),
  );
  return ids
    .map((id) => byId.get(id))
    .filter((proposition): proposition is Proposition => proposition !== undefined)
    .map(interpretationSlot);
}

function wellFormedCommand(command: SubmitTurnCommand): boolean {
  if (typeof command.case_id !== 'string' || command.case_id.trim().length === 0) return false;
  if (!Array.isArray(command.in_reply_to)) return false;
  if (command.in_reply_to.some((value) => typeof value !== 'string' || value.length === 0)) {
    return false;
  }
  // `null` means "no exact transport retry identity, heuristic fallback may
  // apply" and stays valid. An empty or blank string is not an identity at
  // all: committed as one, every later submission carrying the same blank key
  // exact-matches the first operation and replays its result regardless of
  // text, requirements, provenance or version — silently dropping a real
  // answer. It is refused rather than repaired into `null`, because an adapter
  // that sends one is broken and should be told so.
  if (command.client_turn_id !== null && !isClientIssuedId(command.client_turn_id)) return false;
  const payload: unknown = command.payload;
  if (typeof payload !== 'object' || payload === null) return false;
  const { context, answer } = payload as Partial<SourceTurnPayload>;
  if (!Array.isArray(context)) return false;
  if (context.some((message) => typeof message?.text !== 'string')) return false;
  return typeof answer?.text === 'string';
}

function buildWarnings(
  acceptedCount: number,
  facts: { opened: number; translated: boolean },
): string[] {
  const warnings: string[] = [];
  if (facts.opened > 0) {
    warnings.push('JuryAI needs a clarification before it can record an answer to that question.');
  } else if (acceptedCount === 0) {
    warnings.push('JuryAI did not record a canonical statement from that answer.');
  }
  if (facts.translated) {
    // Span fidelity is a claim about the material JuryAI received. A relay that
    // says it translated the answer has removed that claim's meaning, and the
    // record says so rather than quietly keeping the same standing.
    warnings.push(
      'That answer was relayed as a translation, so JuryAI cannot tie its wording to the words you used.',
    );
  }
  return warnings;
}
